import type { Metadata } from "next";
import { Geist, Geist_Mono, Ysabeau_SC } from "next/font/google"; 
import "./globals.css";
import { Header } from "@/widgets/header";
import { Footer } from "@/widgets/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const ysabeau = Ysabeau_SC({
  variable: "--font-ysabeau",
  subsets: ["latin"],
  weight: ["400","500","600","700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
        className={`${geistSans.variable} ${geistMono.variable} ${ysabeau.variable} antialiased`}
      > 
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
